### ISSUE TITLE
"tar: invalid tar magic" when deploying to Deis

### ISSUE THREAD

**Issue by mboersma** [deis/example-php#4]
`git push deis master` of example-php currently fails:
```console
...
Step 5 : ENV GIT_SHA 3c8688373922067ff936ad31ebbcfee60034dfe6
 ---> Running in d94c1666f10f
 ---> 5eeed9c57064
Removing intermediate container d94c1666f10f
Successfully built 5eeed9c57064
-----> Pushing image to private registry

tar: invalid tar magic
To ssh://git@deis.local3.deisapp.com:2222/upbeat-dragster.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'ssh://git@deis.local3.deisapp.com:2222/upbeat-dragster.git'
```

The [php-getting-started](https://github.com/heroku/php-getting-started) example works fine, however, so I assume it's a problem with this app.

**Comment by dpanelli** [comment]
Hello ,
we just upgraded to 1.7.2 and we 're getting this error with the scala buildpack , any hint  on how to solve?

**Comment by Joshua-Anderson** [comment]
@dpanelli Do you have a `Procfile`? `invalid tar magic` often comes up when you don't have a `Procfile` for your app.

**Comment by dpanelli** [comment]
No, I don't have a Procfile ( it's a Play 2.4 app ) and before the Deis (v.1.5) upgrade it was working fine.
Any new push is resulting in such error. 
Maybe a change in the buildpack?

**Comment by Joshua-Anderson** [comment]
It seems to be a deis bug of some sort, as it affects every buildpack. Adding a `Procfile` should fix it.

**Comment by dpanelli** [comment]
Added the Procfile:
web: target/universal/stage/bin/api-registry -Dhttp.port=$PORT
But the issue is still there :(

**Comment by Joshua-Anderson** [comment]
Could you please open a issue at the [main deis issue tracker](https://github.com/deis/deis/issues) so that we can track this?

**Comment by dpanelli** [comment]
Sure.Created on the main issue tracker.
